### ISSUE TITLE
LiSendMousePositionEvent with multiple host monitors

### ISSUE THREAD

**Issue by tomblind** [moonlight-stream/nvidia-gamestream-issues#1]
I started playing with this for touchscreen support on moonlight-embedded, but have run into some odd behavior when the host computer has multiple monitors. Instead of mapping the mouse position from the reference size to the monitor being streamed, the coordinate is being mapped to the entire area covered by all screens.

For example, if I have two screens (same resolution) side by side and I send a coordinate in the middle of the client's screen (referenceWidth / 2), the mouse cursor will be placed on the right edge of the host screen being streamed. However, moving past that point does not actually put the mouse cursor on the other monitor. This leads me to suspect it's not intentional behavior.

**Comment by mariotaku** [comment]
GeForce Experience 3.22.0.32 may have fixed this issue. Mouse pointer behaves correctly on moonlight-tv.

**Comment by cgutman** [comment]
Yep, can confirm this locally. Fixed in GFE 3.22 and RTX Experience 1.3.
