### ISSUE TITLE
Moonlight streams wrong monitor.

### ISSUE THREAD

**Issue by naidoo88** [moonlight-stream/nvidia-gamestream-issues#22]
As in the title.  I have a dual monitor set up. 

Unless I disconnect the second monitor and reboot my PC, moonlight will prefer the wrong monitor.

Games launch on the correct monitor, on the host PC, as this is set as my Primary Display in windows.

In case it is relevant:

- I have a GTX 970
- The secondary monitor is oriented vertically
- The secondary monitor uses a HDMI connection
- The primary monitor uses a DVI connection
- Both monitors are 1080p
- This is true for any game (or manually added executable) launched through moonlight

It's really inconventient needing to get behind my PC to connect/disconnect my HDMI cable any time I want to stream, and the wear and tear on the port makes me nervous in this economy!

Any help or suggestions would be deeply appreciated, and just let me know if I can provide any further info.

Thanks!

**Comment by naidoo88** [comment]
Thank you for that clarification.

It lead me down another search engine rabbithole which lead me to a [solution ](https://lighthouse.thecloudiest.com/2020/12/20/fix-nvidia-shield-moonlight-selecting-the-wrong-monitor/) to the problem.  In case the page dissappears for some reason, I've summarised the steps below:

1. Ensure your primary monitor is the BIOS primary display (the one the logo appears on on boot.
2. (Suggested) Make a windows restore point, just in case.
3. Unplug every monitor except your primary display.
3. Open Registry Editor.
4. Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Configuration`.
5. Delete all sub-items under Configuration.
6. Reboot your machine.
7. Reconnect your other monitors.
8. Profit.

Hope this helps anyone finding this in searches in the future.

I leave it to your disgretion as to whether this should remain open. 
In my ignorance, I don't understand why GeForce Experience wouldn't simply respect Window's "Primary Monitor" selection, like all the games you launch do.

EDIT:
Just to add in aid of anyone else who finds this, performing a "clean install" of the latest Nvidia Driver undid these changes, and I had to repeat the above.

**Comment by Xecular** [comment]
Discovered a solution that worked for me which doesn't require editing the registry

1. Enter NVIDIA Control Panel
2. Go to "Set up multiple displays" under display settings
3. Right click the monitor you want to be streamed
4. Select "Make Primary"
5. Apply

**Comment by naidoo88** [comment]
At the time, of posting this was the case for me too.  The wrong monitor was still streamed.
The next time there is a driver update I'll do a clean install and try it again and report back.

**Comment by dmrickey** [comment]
> Discovered a solution that worked for me which doesn't require editing the registry
> 
> 1. Enter NVIDIA Control Panel
> 2. Go to "Set up multiple displays" under display settings
> 3. Right click the monitor you want to be streamed
> 4. Select "Make Primary"
> 5. Apply

My desired monitor was/is already set to primary. I swapped it around and this didn't help at all

**Comment by naidoo88** [comment]
> My desired monitor was/is already set to primary. I swapped it around and this didn't help at all

This was the case for me (as in the original post).
Have you tried the [steps I posted above](https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/22#issuecomment-1010348630)?

**Comment by roughnecks** [comment]
This is fixed for me with Nvidia Studio Driver 516.59, released today.

Honestly, I didn't try anymore since when it happened to me, so could be it's not related to this driver version, but first thing I tried after upgrading was trying the record desktop feature (shadowplay) and it worked on my main monitor - so I upgraded Moonlight on my Steam Link and tried there too (working fine).

**Comment by Sushygore** [comment]
Hi! I stumbled upon a solution, if it helps anybody :
- In Moonlight config, set GUI to Fullscreen. It should put itself on the monitor it defaults to (at least, that's what happened in my case)
- Shift + Windows key + Arrow key to set the GUI to the desired monitor
- Connect to your desired Moonlight VM/App
Hopefully it helps :) Have a good one!

**Comment by USBhost** [comment]
> This is fixed for me with Nvidia Studio Driver 516.59, released today.
> 
> Honestly, I didn't try anymore since when it happened to me, so could be it's not related to this driver version, but first thing I tried after upgrading was trying the record desktop feature (shadowplay) and it worked on my main monitor - so I upgraded Moonlight on my Steam Link and tried there too (working fine).

Normal game ready 516.xx fixed it for me.

**Comment by KINGLIFER** [comment]
> 

This is confusing. What you mean moonlight config set GUI to fullscreen? If you are using moonlight that is the client. How does that make GFE send to the correct monitor?

**Comment by scyto** [comment]
> At the time, of posting this was the case for me too. The wrong monitor was still streamed. The next time there is a driver update I'll do a clean install and try it again and report back.

This was working in windows 11 for me. It no longer works on insider build 25276 (just in case anyone ends up here with same issue).

**Comment by KINGLIFER** [comment]
Hey guys listen i gave up and went with Sunshine. Works like a charm. Here is a sort of detailed way how to fix the monitor issue and be at peace. 
https://www.reddit.com/r/GeForceExperience/comments/10crfe5/wanted_to_share_my_setup_using_nvidia_shield_with/

**Comment by naidoo88** [comment]
@scyto good to know, annoying that windows has somehow broken it... but I guess it doesn't matter much with GameStream being removed.  Nice to know things are working in Sunshine when I make the switch @KINGLIFER.

Given that as of next month this will be redundant, I will close the thread.  I hope the fix was of use to people while it stood.

See you all on the other side in Sunshine :)
