### ISSUE TITLE
Remote application and stream closes unexpectedly

### ISSUE THREAD

**Issue by qbyss** [moonlight-stream/nvidia-gamestream-issues#34]
Client is using Moonlight 4.1.0 on macOS 12.4 on a macbook Pro 16' M1 Pro.
Host is a Windows 10 Home 64bits 21H2 with a RTX 3080. GFE 3.25.1.27. Drivers are 516.59. No additional firewall/antivirus.
I have a second screen plugged on the HDMI but not turned on. 

I use a 802.11ax connection and have a stable 700 Mbps bitrate.
I'm also using Moonlight default setting but tried every options there was to see if it improved anything, it doesn't. I'm usually streaming at 1440p/120hz.

My issue is that when I use moonlight is that after few minutes (could be 1, could be 40- The stream and the remote application close themselves. It's not a disconnection issue, both machines can ping internet while this happens.
I have Windows 10 device disconnection sound just before the stream crash.

Moonlight log is like that: 

```
00:26:24 - SDL Info (0): Requesting IDR frame on behalf of DR
00:26:24 - SDL Info (0): IDR frame request sent
00:26:24 - SDL Info (0): Waiting for IDR frame
00:26:24 - SDL Info (0): Waiting for IDR frame
00:30:15 - SDL Info (0): Server notified termination reason: 0x80030023
00:30:15 - SDL Error (0): Connection terminated: 0
00:30:15 - SDL Info (0): Quit event received
00:30:15 - SDL Info (0): Global video stats
00:30:15 - SDL Info (0): ----------------------------------------------------------
```

And gamestream logs always give me that : 

```
Termination reason = SERVER_TERMINATED_DISPLAY_TOPOLOGY_CHANGED (SRC_DisplayTopologyChanged)
...
<Fbc7FrameProvide> Capture failure, reported capture resolution is 0 x 0 pitch 0. Writing a black frame.
<Fbc7FrameProvide> Capture resolution is now 1280 x 720 pitch 0.
<Fbc7FrameProvide> Failed to grab frame as the session was invalidated.
<Fbc7FrameProvide> FBC session invalidated with internal error code 0xfbce0004.
<Fbc7FrameProvide> Attempting to recreate FBC session.
<Fbc7FrameProvide> Driver reports that device was lost.
<Fbc7FrameProvide> Recreate the pipeline to recover from this situation
<Fbc7FrameProvide> Failed to grab frame: -3 (NVFBC_ERROR_INVALIDATED_SESSION).
```

I've attached a log when it happens with mstsc (but it also happened with Hitman III, I can give the log if necessary)
[NvStreamer_mtsc.log](https://github.com/moonlight-stream/moonlight-qt/files/9077560/NvStreamer_mtsc.log)

Other than that it works flawlessly and it's a shame, especially because the application is killed so I lose my game if I didn't save prior to that.

**Comment by qbyss** [comment]
I think I found the issue... I guess it's not related to moonlight at all. I had enough clues with the windows disconnect sound. My second screen (LG CX) randomly connect/disconnect and if that happens it kills the stream and closes the application. 
I was able to reproduce that error (the behavior and the error log) by physically plugging in/out the HDMI of the second screen while a stream is working. It also kills the stream on the ipad.

I have no idea why the screen randomly connect/disconnect. I will try to stream with the second screen unplugged and update the issue if this was really the problem, I'm 90% sure it's that.

**Comment by qbyss** [comment]
It's actually not the second screen. Everything is unplugged but I still got the message SERVER_TERMINATED_DISPLAY_TOPOLOGY_CHANGED and the app+stream quits. 

The Windows sound is coming from the NVVHCI Enumerator Unplug, which make sense because it is loosing connection.

At this point I'm clueless. It's just so random but it appear way more often when I use the MSTSC link.

**Comment by cgutman** [comment]
Transferring to the Nvidia GameStream issue tracker because it’s a host-side issue rather than a Moonlight bug

**Comment by cgutman** [comment]
Could be a TDR error causing the DirectX device to disappear and come back. Do you see any messages in the Application or System event logs at the time of the issue?

**Comment by qbyss** [comment]
No errors in the event viewer. I checked the logs at the time of the disconnection and nothing. 

I notice that the issue happen when I tend to restart the stream multiple time while messing with the settings or use the remote desktop to start differents applications and switch between windows. If I stick to a game the issue frequency is way lower.

I'm also trying on a fresh Windows installation, so far I didn't have the issue but I didn't use it a lot.

**Comment by cgutman** [comment]
Is your card factory overclocked? I've seen factory overclocked cards where the card is stable while gaming, but breaks when streaming. If so, you can try reducing the GPU clock to see if that fixes the issue.

**Comment by qbyss** [comment]
Currently my afterburner has the GPU clock and Memory Clock both at +0 so it should not be overclocked but I will try to lower it. I doubt it's the issue though. 

Is there any nvidia log where I can have more information about that "topology" error ?

**Comment by cgutman** [comment]
That log you are looking at is the most detailed log I know of. It's possible that there are some in Event Viewer under "Applications and Service Logs" but I'm not sure.

**Comment by qbyss** [comment]
Nothing on the Event Viewer sadly.

I reinstalled a new Windows 10 system and had the exact same problem. So it's most likely hardware related. I will look for this overclock in detail.

**Comment by qbyss** [comment]
I've noticed that if I set the computer on second screen only (LG CX) and if the stream crash at that moment the TV goes black and then it restart with the Game Mode message like usual. As if the driver crashed. But I haven't seen that behavior on my PC screen.

**Comment by qbyss** [comment]
So I finally found the solution. It was the windows GPU Scheduler. Since I've disabled it, everything works like a charm.
